### PR TITLE
chore: Upgrade kpt

### PR DESCRIPTION
**Pull request by msvticket**

### CODE REVIEW

**Comment by msvticket** [comment]
I guess that merging this would make the Release for jx3-versions go through. Another option would be to expose the docker engine to the build.

**Comment by ankitm123** [comment]
May be remove the upgrade from jx3-versions release? it's not like we use this anymore ... and no immediate plans to revive LTS going forward ...

**Comment by msvticket** [comment]
Fine with me. I can do it. I'll leave the PR here in case we change our mind.

**Pull request closed without merging**
